application:
  rest:
    context-path: /api
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:8081,http://192.168.1.12:8081}

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/phone_shop
    username: chiva
    password: chiva2018
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQL81Dialect

#spring:
#  datasource:
#    url:  jdbc:mysql://localhost:3306/phone_shop
#    username: root
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect:  org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    serialization:
      fail-on-empty-beans : false