application:
  rest:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:8081,http://192.168.1.12:8081}

server:
  servlet:
    context-path: /api

spring:
  datasource:
    url:  ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQL81Dialect

  jackson:
    serialization:
      fail-on-empty-beans : false

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${RABBIT_VIRTUAL_HOST}

opentracing:
  jaeger:
    http-sender:
      url: ${JAEGER_URL}
      max-payload: 16486100
    remote-reporter:
      max-queue-size: 1000
    const-sampler:
      decision: true
    expand-exception-logs: true


rabbitmq:
  notification:
    exchange: ps.notification.exchange.topic
    multi-message:
      queue: ps.notification.queue.multi-message
      routing-key: ps.notification.key.multi-message
    multi-message.error:
      queue: ps.notification.queue.multi-message.error
      routing-key: ps.notification.key.multi-message.error