spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/phone_shop
    username: chiva
    password: chiva2018
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQL81Dialect



