application:
  rest:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:8081,http://192.168.1.12:8081}

server:
  servlet:
    context-path: /api

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/pg_phone_shop
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQL81Dialect

  jackson:
    serialization:
      fail-on-empty-beans : false

opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
      max-payload: 16486100
    remote-reporter:
      max-queue-size: 1000
    const-sampler:
      decision: true
    expand-exception-logs: true