application:
  rest:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:8081,http://192.168.1.12:8081}

server:
  servlet:
    context-path: /api

spring:
  datasource:
    url:  ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQL81Dialect

  jackson:
    serialization:
      fail-on-empty-beans : false

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-interval: 20s
          max-attempts: 5
          multiplier: 2

opentracing:
  jaeger:
    http-sender:
      url: ${JAEGER_URL}
      max-payload: 16486100
    remote-reporter:
      max-queue-size: 1000
    const-sampler:
      decision: true
    expand-exception-logs: true